sonarQube add to pipelines v5

diff --git a/.github/workflows/pipeline-frontend.yml b/.github/workflows/pipeline-frontend.yml
--- a/.github/workflows/pipeline-frontend.yml
+++ b/.github/workflows/pipeline-frontend.yml
@@ -43,6 +43,87 @@ jobs:
             ${{ secrets.DOCKERHUB_USERNAME }}/gestiondestock-ui:latest
             ${{ secrets.DOCKERHUB_USERNAME }}/gestiondestock-ui:${{ steps.extract_version.outputs.VERSION }}
 
+  lint-check:
+    name: 🧼 Lint Check
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: 📥 Checkout repository
+        uses: actions/checkout@v4
+
+      - name: 📦 Install dependencies
+        run: |
+          cd gestion_stock_ui/hb_electronics
+          npm ci
+
+      - name: 🔍 Run lint
+        run: |
+          cd gestion_stock_ui/hb_electronics
+          npm run lint
+
+
+  sonarqube-analysis:
+      name: SonarQube Frontend Analysis
+      runs-on: ubuntu-latest
+      needs: [build-image, lint-check]
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
+          with:
+            fetch-depth: 0
+
+        - name: Install SonarScanner CLI
+          run: |
+            sudo apt-get update
+            sudo apt-get install -y unzip openjdk-17-jre
+            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
+            unzip sonar-scanner-cli-5.0.1.3006-linux.zip
+            sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
+            sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
+
+        - name: Cache SonarQube packages
+          uses: actions/cache@v4
+          with:
+            path: ~/.sonar/cache
+            key: ${{ runner.os }}-sonar-${{ hashFiles('**/package-lock.json') }}
+            restore-keys: |
+              ${{ runner.os }}-sonar
+
+        - name: Install dependencies and run tests
+          run: |
+            cd gestion_stock_ui/hb_electronics
+            npm ci
+            npx ng test --watch=false --code-coverage --browsers=ChromeHeadless
+
+        - name: Check coverage file presence
+          run: |
+            cd gestion_stock_ui/hb_electronics
+            if [ ! -f coverage/hb_electronics/lcov.info ]; then
+              echo "❌ Coverage report not found!"
+              exit 1
+            fi
+            echo "✅ Coverage report found with $(wc -l < coverage/hb_electronics/lcov.info) lines"
+        
+        - name: Wake up SonarQube (Render)
+          run: curl --silent https://gestionstock-sonarqube.onrender.com > /dev/null || true
+      
+        - name: SonarQube Scan
+          env:
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          run: |
+            cd gestion_stock_ui/hb_electronics
+            sonar-scanner \
+              -Dsonar.projectKey=frontend \
+              -Dsonar.projectName=frontend \
+              -Dsonar.sources=src \
+              -Dsonar.exclusions=src/**/*.spec.ts,**/node_modules/**,**/coverage/**,**/dist/** \
+              -Dsonar.javascript.lcov.reportPaths=coverage/hb_electronics/lcov.info \
+              -Dsonar.host.url=https://gestionstock-sonarqube.onrender.com \
+              -Dsonar.login=$SONAR_TOKEN \
+              -Dsonar.verbose=true
+
+
+
 #Intégrer SonarQube dans un pipeline frontend, c’est comme mettre un contrôle technique automatique sur ton code à chaque push. Ça te protège contre les erreurs subtiles, améliore la lisibilité, et augmente la fiabilité de ton application.
   #deploy:
    # name: Deploy Frontend
